---
# Run the playbook: ansible-playbook deployment.yml -i hosts
- name: This playbook sets up the webserver and deploys the repository
  vars:
    repository: https://github.com/florianmoss/openshift-ireland.git
  hosts: webserver
  become: yes
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: install the latest version of Git
    yum:
      name: git
      state: latest
    
  - name: enable Apache on start
    service:
      name: httpd
      enabled: yes

  - name: ensure httpd is running
    service:
      name: httpd 
      state: started

  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted

  - name: Ensure group "deployment" exists
    group:
      name: deployment
      state: present

  - name: Add the deployment user
    user:
      name: deployment
      group: deployment

  - name: Create websites directory under /home/deployment/
    file:
      path: /home/deployment/websites
      state: directory
      owner: deployment
      group: deployment
      mode: '0755'
  
  - name: Get Repository
    git:
      repo: "{{ repository }}"
      dest: "/home/deployment/websites/sites"

  - name: Copy website to /var/www/html
    copy:
      src: /home/deployment/websites/sites/website/
      dest: /var/www/html
      remote_src: true 
    
  - name: This will restore /var/www's context as determined by SELinux's system policy to /var/www and all folders and files below it.
    command: restorecon -R /var/www
